### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by peachestao** [chipmk/docker-mac-net-connect#17] opened 2022-08-28 13:04 UTC
when i install,report "Error: No such file or directory @ rb_sysopen - /Users/peachestao/Library/Caches/Homebrew/downloads/c9f56865385d7a7687f15959433f3e4dfe0b82ccc48d68897fc4a2ff9595f68e--go-1.17.6.catalina.bottle.tar.gz"。

please help me,thank you.

env:
macos 10.15.7

Here are the details：

```peachestao@peachestaodembp k8s % brew install chipmk/tap/docker-mac-net-connect
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/go-1.17.6.catalina.bottle.tar.gz
#=#=#                                                                         
curl: (22) The requested URL returned error: 404 
Warning: Bottle missing, falling back to the default domain...
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.17.6
Already downloaded: /Users/peachestao/Library/Caches/Homebrew/downloads/5b57f962d64d554b5b211583da67a210451f1999835fc49dd1fa1b2ff349cb16--go-1.17.6.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:f7a522d413b3b5fc47305a3851e0148a63b2786f22796399feb6788af92adb14
Already downloaded: /Users/peachestao/Library/Caches/Homebrew/downloads/4d6c26a099f4ff438e81f0170db10eb13e3c3ae6540f291be331dd9a4056d636--go--1.17.6.catalina.bottle.tar.gz
==> Downloading https://github.com/chipmk/docker-mac-net-connect/archive/refs/tags/v0.1.2.tar.gz
Already downloaded: /Users/peachestao/Library/Caches/Homebrew/downloads/be6ddea4c4a482e7843b5d9af1de1ea1fc218b83ea19a6b12b15081e2ce8983f--docker-mac-net-connect-0.1.2.tar.gz
==> Installing docker-mac-net-connect from chipmk/tap
==> Installing dependencies for chipmk/tap/docker-mac-net-connect: go
==> Installing chipmk/tap/docker-mac-net-connect dependency: go
==> Pouring go-1.17.6.catalina.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/peachestao/Library/Caches/Homebrew/downloads/c9f56865385d7a7687f15959433f3e4dfe0b82ccc48d68897fc4a2ff9595f68e--go-1.17.6.catalina.bottle.tar.gz```

**Comment by gregnr** [comment] 2023-04-14 20:58
Hey @peachestao! Based on your error, I'm trying to understand if this is a `docker-mac-net-connect` issue, or a `brew` issue. Did you ever solve this?

**Comment by gregnr** [comment] 2023-04-21 13:45
Closing for now based on the assumption there was an error with `brew`, but please reopen if you believe the issue is caused by this tool.

**Closed by gregnr** 2023-04-21 13:45 UTC
